Algoritmo "CONTADOR 3"

Var
 contador, numero, intervalo: inteiro
Inicio
 escreva ("Digite o valor a ser repetido: ")
 leia (numero)
 escreva ("Qual será o valor do intervalo: ")
 leia (intervalo)
        contador <- 0
        enquanto ( contador <= numero) faca
                 escreval (contador)
                 contador <- (contador + intervalo)
        fimenquanto
 escreva ("Terminei de contar.")
Fimalgoritmo